name: Image Build and Test

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "30 22 * * *"


jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Build the Docker image
        run: docker build . --file Dockerfile --build-arg OPT_PDF=1


 
